// This file is auto-generated by @hey-api/openapi-ts

export type Body_documents_upload_document = {
    file: string;
    title?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ChatMessageCreate = {
    content: string;
};

export type ChatMessagePublic = {
    content: string;
    id: string;
    role: ChatMessageRole;
    created_at?: (string | null);
};

export type ChatMessageRole = 'user' | 'assistant';

export type ChatMessagesPublic = {
    data: Array<ChatMessagePublic>;
    count: number;
};

export type ChatResponse = {
    user_message: ChatMessagePublic;
    assistant_message: ChatMessagePublic;
};

export type DocumentCreate = {
    title: string;
    file_path: string;
};

export type DocumentPublic = {
    title: string;
    id: string;
    status: DocumentStatus;
    file_path: string;
    created_at?: (string | null);
    extracted_data?: ({
    [key: string]: unknown;
} | null);
};

export type DocumentsPublic = {
    data: Array<DocumentPublic>;
    count: number;
};

export type DocumentStatus = 'pending' | 'processing' | 'completed' | 'failed';

export type DocumentUpdate = {
    title?: (string | null);
    status?: (DocumentStatus | null);
    file_path?: (string | null);
    extracted_data?: ({
    [key: string]: unknown;
} | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserRole = 'viewer' | 'moderator';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ChatReadChatMessagesData = {
    limit?: number;
    skip?: number;
};

export type ChatReadChatMessagesResponse = (ChatMessagesPublic);

export type ChatSendChatMessageData = {
    requestBody: ChatMessageCreate;
};

export type ChatSendChatMessageResponse = (ChatResponse);

export type DocumentsReadDocumentsData = {
    limit?: number;
    skip?: number;
};

export type DocumentsReadDocumentsResponse = (DocumentsPublic);

export type DocumentsCreateDocumentData = {
    requestBody: DocumentCreate;
};

export type DocumentsCreateDocumentResponse = (DocumentPublic);

export type DocumentsUploadDocumentData = {
    formData: Body_documents_upload_document;
};

export type DocumentsUploadDocumentResponse = (DocumentPublic);

export type DocumentsReadDocumentData = {
    id: string;
};

export type DocumentsReadDocumentResponse = (DocumentPublic);

export type DocumentsUpdateDocumentData = {
    id: string;
    requestBody: DocumentUpdate;
};

export type DocumentsUpdateDocumentResponse = (DocumentPublic);

export type DocumentsDeleteDocumentData = {
    id: string;
};

export type DocumentsDeleteDocumentResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);